DELETE FROM itm_merch_hierarchy_level
  WHERE organization_id = 1;
  
Insert into ITM_MERCH_HIERARCHY_LEVELS (ORGANIZATION_ID,LEVEL_ID,LEVEL_CODE,DESCRIPTION,CREATE_USER_ID,CREATE_DATE,UPDATE_USER_ID,UPDATE_DATE,RECORD_STATE) values (1,1,'DEPARTMENT','+MERCHLEVEL1','BASEDATA',GETUTCDATE(),'ASQBDATA',GETUTCDATE(),null);
Insert into ITM_MERCH_HIERARCHY_LEVELS (ORGANIZATION_ID,LEVEL_ID,LEVEL_CODE,DESCRIPTION,CREATE_USER_ID,CREATE_DATE,UPDATE_USER_ID,UPDATE_DATE,RECORD_STATE) values (1,2,'SUBDEPARTMENT','+MERCHLEVEL2','ASQBDATA',GETUTCDATE(),'ASQBDATA',GETUTCDATE(),null);
Insert into ITM_MERCH_HIERARCHY_LEVELS (ORGANIZATION_ID,LEVEL_ID,LEVEL_CODE,DESCRIPTION,CREATE_USER_ID,CREATE_DATE,UPDATE_USER_ID,UPDATE_DATE,RECORD_STATE) values (1,3,'CLASS','+MERCHLEVEL3','ASQBDATA',GETUTCDATE(),'ASQBDATA',GETUTCDATE(),null);
Insert into ITM_MERCH_HIERARCHY_LEVELS (ORGANIZATION_ID,LEVEL_ID,LEVEL_CODE,DESCRIPTION,CREATE_USER_ID,CREATE_DATE,UPDATE_USER_ID,UPDATE_DATE,RECORD_STATE) values (1,4,'SUBCLASS','+MERCHLEVEL4','ASQBDATA',GETUTCDATE(),'ASQBDATA',GETUTCDATE(),null);
