package asq.pos.common;

public interface AsqConstant {

	String ASQ_TOLA_MAX_WEIGHT = "MAX_SALE_UNIT_COUNT";
	String ASQ_TOLA_MIN_WEIGHT = "MIN_SALE_UNIT_COUNT";

	String ASQ_LAST_TOLA_WEIGHT_ENT = "Last_Weight_Entered_";

	String ASQ_TOLA = "TOLA";
	String ASQ_HTOLA = "HTOLA";
	String ASQ_QTOLA = "QTOLA";
	String ASQ_2TOLA = "2TOLA";
	String ASQ_3TOLA = "3TOLA";
	String ASQ_5TOLA = "5TOLA";
	String ASQ_10TOLA = "10TOLA";
	String ASQ_TOLA_WEIGHT_RANGE_ERROR = "ASQ_TOLA_WEIGHT_RANGE_ERROR";
	String ASQ_TOLA_QTY_SOH_ERROR = "ASQ_TOLA_QTY_SOH_ERROR";

	// Register Close Receiving Validation rule
	String ASQ_RECEIVING_REG_CLOSE_MSG = "_asqShippingIsInProgressValidation";
	String ASQ_RECEIVING_REG_CLOSE_QRY = "ASQ_IN_PROGRESS_RECEIVING";

	String ASQ_GET_EMPLOYEE_COMM_NETSALE_QRY = "ASQ_EMPLOYEE_COMMISSION_QUERY";

	String ASQ_GET_EMPLOYEE_ITEM_COMM_NETSALE_QRY = "ASQ_EMPLOYEE_ITEM_COMMISSION_QUERY";

	String ASQ_ON_HAND = "ON_HAND";
	String ASQ_DEFAULT = "DEFAULT";

	String ASQ_ITEM_COMMISSION = "ASQ_ITEM_COMMISSION";
	String ASQ_STORE_SALE_COMMISSION = "ASQ_STORE_SALE_COMMISSION";

	String ASQ_INVENTORY_TOLA_ITEM = "INVENTORY_TOLA_ITEM";
	String ASQ_INVENTORY_TOLA_ITEM_WEIGHT = "INVENTORY_TOLA_ITEM_WEIGHT";

}
