-- ***************************************************************************
-- Place any customer data that must be incorporated into the build into this file
--
-- All sql statements that goes here should be defined in a update-safe way, ie. the final script should be able 
-- to run against the database any number of times and should produce the same output.
--
-- This file should finish with a database commit; at least at the end of the file.
-- 
-- ***************************************************************************

-- ***************************************************************************
-- Oracle db specific command. Remove or comment this line out for all other DBMS.
ALTER SESSION SET CURRENT_SCHEMA=$(DbSchema);
-- ***************************************************************************

-- *******************************************
-- Default Employee
-- *******************************************
DELETE FROM CRM_PARTY WHERE organization_id = 1 AND party_id = 0;
INSERT INTO crm_party (organization_id, party_id, employee_id, last_name, party_typcode, create_date, create_user_id, update_date, update_user_id) 
  VALUES ($(OrgID) , 0, 0, 'ASQ SYSTEM USER', 'SYSTEM', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

DELETE FROM crm_party_locale_information WHERE organization_id = 1 AND party_id = 0 AND party_locale_seq <= 1;
INSERT INTO crm_party_locale_information (organization_id, party_id, party_locale_seq, primary_flag, address1, city, state, postal_code, country, create_date, create_user_id, update_date, update_user_id)
  VALUES ($(OrgID) , 0, 1, 1, 'طريق الامير سلطان، السلامة، جدة ', 'Jeddah', 'Makkah', '21955', 'SA', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

DELETE FROM crm_party_telephone WHERE organization_id = 1 AND party_id = 0 AND telephone_type in ('Home', 'HOME');
INSERT INTO crm_party_telephone (organization_id, party_id, telephone_type, telephone_number, create_date, create_user_id, update_date, update_user_id)
  VALUES ($(OrgID) , 0, 'HOME', '+966 126 599 569', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

DELETE FROM hrs_employee WHERE organization_id = 1 AND employee_id = '0';
INSERT INTO hrs_employee (organization_id, employee_id, login_id, party_id, job_title, employee_role_code, group_membership,
      primary_group, employee_typcode, training_status_enum,  employee_statcode, create_date, create_user_id, update_date, update_user_id)
  VALUES ($(OrgID) , '0', '0', 0, 'ASQ SYSTEM USER', 'EVERYONE', 'AQ==', 'EVERYONE', 'EVERYONE', 'EXEMPT', 'A', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

-- *******************************************
-- Default Employee 100
-- *******************************************
DELETE FROM CRM_PARTY WHERE organization_id = 1 AND party_id = 100;
INSERT INTO crm_party (organization_id, party_id, employee_id, last_name, party_typcode, create_date, create_user_id, update_date, update_user_id) 
  VALUES ($(OrgID) , 100, 100, 'ASQ LOGIN USER', 'SYSTEM', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

DELETE FROM hrs_employee WHERE organization_id = 1 AND employee_id = '100';
INSERT INTO hrs_employee (organization_id, employee_id, login_id, party_id, job_title, employee_role_code, group_membership,
      primary_group, employee_typcode, training_status_enum,  employee_statcode, create_date, create_user_id, update_date, update_user_id)
  VALUES ($(OrgID) , '100', '100', 100, 'ASQ LOGIN USER', 'EVERYONE', 'AQ==', 'EVERYONE', 'EVERYONE', 'EXEMPT', 'A', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
  
DELETE FROM hrs_employee_password WHERE organization_id = $(OrgID) AND employee_id = '100';
INSERT INTO hrs_employee_password (organization_id, employee_id, password, effective_date, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , '100', '{SHA512}a8f51fd86e36fa6b49da51438cc2fb3051b3f86323f6ab043ef67ef713d1a0e5f8cd95ecbbbae65000bcf3d0f8cfe11e54d764ed413a6f5314c6ad9fcc5f0400$d462287e74820bed$100000', GETUTCDATE(), GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

DELETE FROM hrs_employee_store WHERE organization_id = $(OrgID) AND employee_id = '100';
INSERT INTO hrs_employee_store (organization_id, rtl_loc_id, employee_id, employee_store_seq, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , $(StoreID), '100', 0, GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

DELETE FROM crm_party_locale_information WHERE organization_id = 1 AND party_id = 100 AND party_locale_seq <= 1;
INSERT INTO crm_party_locale_information (organization_id, party_id, party_locale_seq, primary_flag, address1, city, state, postal_code, country, create_date, create_user_id, update_date, update_user_id)
  VALUES ($(OrgID) , 100, 2, 1, 'طريق الامير سلطان، السلامة، جدة ', 'Jeddah', 'Makkah', '21955', 'SA', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

DELETE FROM crm_party_telephone WHERE organization_id = 1 AND party_id = 100 AND telephone_type in ('Home', 'HOME');
INSERT INTO crm_party_telephone (organization_id, party_id, telephone_type, telephone_number, create_date, create_user_id, update_date, update_user_id)
  VALUES ($(OrgID) , 100, 'HOME', '+966 126 599 569', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

-- *******************************************
-- Tender Type code
-- *******************************************
DELETE FROM loc_wkstn WHERE organization_id = 1 AND rtl_loc_id = '$(StoreID)';  
INSERT INTO loc_wkstn (organization_id, rtl_loc_id, wkstn_id, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , $(StoreID), 1, GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

-- *******************************************
-- Tender Type code
-- *******************************************
DELETE FROM TND_TNDR_TYPCODE WHERE organization_id = 1;

INSERT INTO tnd_tndr_typcode (organization_id, tndr_typcode, description, sort_order, unit_count_req_code, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), 'ACCOUNT', '+TND_TNDR_TYPCODE_ACCOUNT', 60, 'TOTAL_NORMAL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO tnd_tndr_typcode (organization_id, tndr_typcode, description, sort_order, unit_count_req_code, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), 'ACCOUNT_CREDIT', '+TND_TNDR_TYPCODE_ACCOUNT_CREDIT', 10, 'TOTAL_NORMAL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO tnd_tndr_typcode (organization_id, tndr_typcode, description, sort_order, unit_count_req_code, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), 'CURRENCY', '+TND_TNDR_TYPCODE_CURRENCY', 0, 'DENOMINATION', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO tnd_tndr_typcode (organization_id, tndr_typcode, description, sort_order, unit_count_req_code, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), 'CREDIT_CARD', '+TND_TNDR_TYPCODE_CREDIT_CARD', 20, 'TOTAL_NORMAL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO tnd_tndr_typcode (organization_id, tndr_typcode, description, sort_order, unit_count_req_code, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), 'MISCELLANEOUS', '+TND_TNDR_TYPCODE_MISCELLANEOUS', 40, 'TOTAL_NORMAL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO tnd_tndr_typcode (organization_id, tndr_typcode, description, sort_order, unit_count_req_code, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), 'MISCELLANEOUS_VOUCHER', '+TND_TNDR_TYPCODE_MISCELLANEOUS_VOUCHER', 45, 'TOTAL_NORMAL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO tnd_tndr_typcode (organization_id, tndr_typcode, description, sort_order, unit_count_req_code, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), 'VOUCHER', '+TND_TNDR_TYPCODE_VOUCHER', 80, 'TOTAL_SHORT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO tnd_tndr_typcode (organization_id, tndr_typcode, description, sort_order, unit_count_req_code, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), 'DEBIT_CARD', '+TND_TNDR_TYPCODE_DEBIT_CARD', 100, 'TOTAL_NORMAL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO tnd_tndr_typcode (organization_id, tndr_typcode, description, sort_order, unit_count_req_code, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), 'PAY_BY_LINK', '+TND_TNDR_TYPCODE_PAY_BY_LINK', 50, 'TOTAL_NORMAL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO tnd_tndr_typcode (organization_id, tndr_typcode, description, sort_order, unit_count_req_code, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), 'LOYALITY', '+TND_TNDR_TYPCODE_LOYALITY', 20, 'TOTAL_NORMAL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO tnd_tndr_typcode (organization_id, tndr_typcode, description, sort_order, unit_count_req_code, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), 'MISCELLANEOUS_EFTLINK', '+TND_TNDR_TYPCODE_MISCELLANEOUS_EFTLINK', 140, 'TOTAL_NORMAL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO tnd_tndr_typcode (organization_id, tndr_typcode, description, sort_order, unit_count_req_code, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), 'COUPON', '+TND_TNDR_TYPCODE_COUPON', 30, 'TOTAL_SHORT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

-- ************************************
-- COM Transalation for tender Arabic
-- ************************************
DELETE FROM com_translations WHERE organization_id = $(OrgID) AND translation_key='+TND_TNDR_TYPCODE_ACCOUNT';
INSERT INTO com_translations (organization_id, translation_key, locale, org_code, org_value, translation, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), '+TND_TNDR_TYPCODE_ACCOUNT', 'AR', '*', '*', 'الحساب', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
DELETE FROM com_translations WHERE organization_id = $(OrgID) AND translation_key='+TND_TNDR_TYPCODE_ACCOUNT_CREDIT';
INSERT INTO com_translations (organization_id, translation_key, locale, org_code, org_value, translation, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), '+TND_TNDR_TYPCODE_ACCOUNT_CREDIT', 'AR', '*', '*', 'ائتمان الحساب مثل طرق حجز البضاعة', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
DELETE FROM com_translations WHERE organization_id = $(OrgID) AND translation_key='+TND_TNDR_TYPCODE_COUPON';
INSERT INTO com_translations (organization_id, translation_key, locale, org_code, org_value, translation, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), '+TND_TNDR_TYPCODE_COUPON', 'AR', '*', '*', 'كوبون', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
DELETE FROM com_translations WHERE organization_id = $(OrgID) AND translation_key='+TND_TNDR_TYPCODE_CREDIT_CARD';
INSERT INTO com_translations (organization_id, translation_key, locale, org_code, org_value, translation, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), '+TND_TNDR_TYPCODE_CREDIT_CARD', 'AR', '*', '*', 'بطاقة الائتمان', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
DELETE FROM com_translations WHERE organization_id = $(OrgID) AND translation_key='+TND_TNDR_TYPCODE_CURRENCY';
INSERT INTO com_translations (organization_id, translation_key, locale, org_code, org_value, translation, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), '+TND_TNDR_TYPCODE_CURRENCY', 'AR', '*', '*', 'عملة', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
DELETE FROM com_translations WHERE organization_id = $(OrgID) AND translation_key='+TND_TNDR_TYPCODE_MISCELLANEOUS';
INSERT INTO com_translations (organization_id, translation_key, locale, org_code, org_value, translation, create_date, create_user_id, update_date, update_user_id) VALUE ($(OrgID), '+TND_TNDR_TYPCODE_MISCELLANEOUS', 'AR', '*', '*', 'المتنوعات', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
DELETE FROM com_translations WHERE organization_id = $(OrgID) AND translation_key='+TND_TNDR_TYPCODE_MISCELLANEOUS_VOUCHER';
INSERT INTO com_translations (organization_id, translation_key, locale, org_code, org_value, translation, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), '+TND_TNDR_TYPCODE_MISCELLANEOUS_VOUCHER', 'AR', '*', '*', 'إيصال المتنوعات', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
DELETE FROM com_translations WHERE organization_id = $(OrgID) AND translation_key='+TND_TNDR_TYPCODE_VOUCHER';
INSERT INTO com_translations (organization_id, translation_key, locale, org_code, org_value, translation, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), '+TND_TNDR_TYPCODE_VOUCHER', 'AR', '*', '*', 'الإيصال', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
DELETE FROM com_translations WHERE organization_id = $(OrgID) AND translation_key='+TND_TNDR_TYPCODE_MISCELLANEOUS_EFTLINK';
INSERT INTO com_translations (organization_id, translation_key, locale, org_code, org_value, translation, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), '+TND_TNDR_TYPCODE_MISCELLANEOUS_EFTLINK', 'AR', '*', '*', 'طريقة دفع EFTLink للمتنوعات', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
DELETE FROM com_translations WHERE organization_id = $(OrgID) AND translation_key='+TND_TNDR_TYPCODE_DEBIT_CARD';
INSERT INTO com_translations (organization_id, translation_key, locale, org_code, org_value, translation, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), '+TND_TNDR_TYPCODE_DEBIT_CARD', 'AR', '*', '*', 'بطاقة الخصم', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
DELETE FROM com_translations WHERE organization_id = $(OrgID) AND translation_key='+TND_TNDR_TYPCODE_PAY_BY_LINK';
INSERT INTO com_translations (organization_id, translation_key, locale, org_code, org_value, translation, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), '+TND_TNDR_TYPCODE_PAY_BY_LINK', 'AR', '*', '*', 'الدفع عن طريق الارتباط', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
DELETE FROM com_translations WHERE organization_id = $(OrgID) AND translation_key='+TND_TNDR_TYPCODE_LOYALITY';
INSERT INTO com_translations (organization_id, translation_key, locale, org_code, org_value, translation, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), '+TND_TNDR_TYPCODE_LOYALITY', 'AR', '*', '*', 'الولاء', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

-- *************************
-- Session Store Data
-- *************************
DELETE FROM TSN_TNDR_REPOSITORY 
  WHERE organization_id = 1 AND 
        rtl_loc_id = $(StoreID) AND 
        tndr_repository_id IN ('STOREBANK', 'DEPOSIT_BANK','001');

INSERT INTO tsn_tndr_repository (organization_id, tndr_repository_id, rtl_loc_id, typcode, 
      not_issuable_flag, name, dflt_wkstn_id, create_date, create_user_id, update_date, update_user_id)
  VALUES ($(OrgID) , 'STOREBANK', $(StoreID), 'STOREBANK', 1, 'Store Safe', NULL, GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

INSERT INTO tsn_tndr_repository (organization_id, tndr_repository_id, rtl_loc_id, typcode, 
      not_issuable_flag, name, description, create_date, create_user_id, update_date, update_user_id)
  VALUES ($(OrgID) , 'DEPOSIT_BANK', $(StoreID), 'BANK', 1, 'Deposit Bank', '+TSN_TNDR_REPOSITORY_DEPOSIT_BANK', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

INSERT INTO tsn_tndr_repository (organization_id, tndr_repository_id, rtl_loc_id, typcode, 
      not_issuable_flag, name, dflt_wkstn_id, create_date, create_user_id, update_date, update_user_id)
  VALUES ($(OrgID) , '001', $(StoreID), 'TILL', 0, 'ASQ Default Registor 001', 1, GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
   
DELETE FROM com_translations WHERE organization_id = $(OrgID) AND translation_key='+TSN_TNDR_REPOSITORY_DEPOSIT_BANK';
INSERT INTO com_translations (organization_id, translation_key, locale, org_code, org_value, translation, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID), '+TSN_TNDR_REPOSITORY_DEPOSIT_BANK', 'AR', '*', '*', 'بنك الإيداع', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
  
-- *******************************************
-- Store safe session
-- *******************************************
DELETE FROM tsn_session WHERE organization_id = 1 AND rtl_loc_id = $(StoreID) AND session_id = 0;
INSERT INTO tsn_session (organization_id, rtl_loc_id, session_id, employee_party_id, statcode, tndr_repository_id, create_date, create_user_id, update_date, update_user_id)
  VALUES ($(OrgID), $(StoreID), 0, NULL, 'ENDCOUNT', 'STOREBANK', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
  
-- *******************************************
-- Default privilege
-- *******************************************  
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'VIEW_AND_EDIT_CUSTOMER_GROUPS', 0, 0, 'AQ==', '_secPrivilege_VIEW_AND_EDIT_CUSTOMER_GROUPS', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'ACCEPT_WARRANTY_NOT_ON_FILE', 0, 1, 'EA==', '_secPrivilege_ACCEPT_WARRANTY_NOT_ON_FILE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'ACCESS_OTHER_TILLS', 0, 0, 'EA==', '_secPrivilege_ACCESS_OTHER_TILLS', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'ACTIVATE_SELF_CHECKOUT', 0, 1, 'EA==', '_secPrivilege_ACTIVATE_SELF_CHECKOUT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'ADD_COUPON', 0, 0, 'AQ==', '_secPrivilege_ADD_COUPON', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'ADD_DISCOUNT', 0, 0, 'AQ==', '_secPrivilege_ADD_DISCOUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'ADMINISTRATIVE_WORK_CODE', 0, 0, 'AQ==', '_secPrivilege_ADMINISTRATIVE_WORK_CODE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'ALLOW_EMPLOYEE_SALE', 0, 0, 'AQ==', '_secPrivilege_ALLOW_EMPLOYEE_SALE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'ASSOCIATE_ADVANCE', 0, 0, 'AQ==', '_secPrivilege_ASSOCIATE_ADVANCE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'ASSOCIATE_MAINTAIN', 0, 0, 'AQ==', '_secPrivilege_ASSOCIATE_MAINTAIN', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'ASSOCIATE_SELF_ADVANCE', 0, 0, 'EA==', '_secPrivilege_ASSOCIATE_SELF_ADVANCE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'ATTACH_OTHER_TILL', 0, 0, 'EA==', '_secPrivilege_ATTACH_OTHER_TILL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'ATTACH_TILL', 0, 1, 'AQ==', '_secPrivilege_ATTACH_TILL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'ATTACH_CASHDRAWER_TILL', 0, 1, 'AQ==', '_secPrivilege_ATTACH_CASHDRAWER_TILL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'REMOVE_CASHDRAWER_TILL', 0, 1, 'AQ==', '_secPrivilege_REMOVE_CASHDRAWER_TILL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CANCEL_INVENTORY_COUNT', 0, 1, 'EA==', '_secPrivilege_CANCEL_INVENTORY_COUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CASH_PICKUP', 0, 0, 'EA==', '_secPrivilege_CASH_PICKUP', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CASH_TRANSFER', 0, 0, 'AQ==', '_secPrivilege_CASH_TRANSFER', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CASH_REFUND_EXCEEDS_AVAILABLE_CASH', 0, 1, 'EA==', '_secPrivilege_CASH_REFUND_EXCEEDS_AVAILABLE_CASH', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CHANGE_OTHERS_PASSWORD', 0, 0, 'AQ==', '_secPrivilege_CHANGE_OTHERS_PASSWORD', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CHANGE_OTHERS_QUESTIONS', 0, 0, 'AQ==', '_secPrivilege_CHANGE_OTHERS_QUESTIONS', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CHANGE_PRICE', 0, 0, 'AQ==', '_secPrivilege_CHANGE_PRICE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CHANGE_QUANTITY', 0, 0, 'AQ==', '_secPrivilege_CHANGE_QUANTITY', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CHANGE_SPECIAL_ORDER_EXPECTED_DATE', 0, 1, 'AQ==', '_secPrivilege_CHANGE_SPECIAL_ORDER_EXPECTED_DATE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CHANGE_TAX', 0, 1, 'AQ==', '_secPrivilege_CHANGE_TAX', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CHANGE_TAX_BY_AMOUNT', 0, 0, 'AQ==', '_secPrivilege_CHANGE_TAX_BY_AMOUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CHANGE_TAX_BY_PERCENT', 0, 0, 'AQ==', '_secPrivilege_CHANGE_TAX_BY_PERCENT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CHANGE_TAX_LOCATION', 0, 1, 'AQ==', '_secPrivilege_CHANGE_TAX_LOCATION', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CHANGE_TAX_TO_EXEMPT', 0, 1, 'AQ==', '_secPrivilege_CHANGE_TAX_TO_EXEMPT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CHANGE_TILL_FLOAT', 0, 0, 'AQ==', '_secPrivilege_CHANGE_TILL_FLOAT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CHANGE_VERIFIED_RETURN_ITEM_PRICE', 0, 1, 'EA==', '_secPrivilege_CHANGE_VERIFIED_RETURN_ITEM_PRICE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CLOSE_WITH_SUSPENDED_TRANS', 0, 1, 'AQ==', '_secPrivilege_CLOSE_WITH_SUSPENDED_TRANS', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'COMPLETE_INVENTORY_COUNT', 0, 1, 'EA==', '_secPrivilege_COMPLETE_INVENTORY_COUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'COUPON_REDEEM_FORCE', 0, 1, 'EA==', '_secPrivilege_COUPON_REDEEM_FORCE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'COUPON_REDEEM_OFFLINE', 0, 1, 'EA==', '_secPrivilege_COUPON_REDEEM_OFFLINE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CREATE_CUSTOMER', 0, 0, 'AQ==', '_secPrivilege_CREATE_CUSTOMER', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CREATE_INVENTORY_COUNT', 0, 1, 'EA==', '_secPrivilege_CREATE_INVENTORY_COUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CREATE_SPEC_ORDER', 0, 0, 'AQ==', '_secPrivilege_CREATE_SPEC_ORDER', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CUST_ASSOC', 0, 0, 'AQ==', '_secPrivilege_CUST_ASSOC', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'DELETE_CUSTOMER', 0, 0, 'AQ==', '_secPrivilege_DELETE_CUSTOMER', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'DISABLE_CUST_MSR', 1, 1, 'AQ==', '_secPrivilege_DISABLE_CUST_MSR', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'DISABLE_MICR', 1, 1, 'AQ==', '_secPrivilege_DISABLE_MICR', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'DISABLE_VALIDATION_PRINTER', 1, 1, 'AQ==', '_secPrivilege_DISABLE_VALIDATION_PRINTER', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'DISCOUNT_EXCEED_MAX_THRESHOLD', 0, 1, 'AQ==', '_secPrivilege_DISCOUNT_EXCEED_MAX_THRESHOLD', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'EDIT_CUSTOMER', 0, 0, 'AQ==', '_secPrivilege_EDIT_CUSTOMER', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'EDIT_LAYAWAY_ITEM', 0, 0, 'AQ==', '_secPrivilege_EDIT_LAYAWAY_ITEM', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'EJOURNAL_ADD_COMMENT', 0, 0, 'AQ==', '_secPrivilege_EJOURNAL_ADD_COMMENT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'EJOURNAL_GIFT_RECEIPT', 0, 0, 'AQ==', '_secPrivilege_EJOURNAL_GIFT_RECEIPT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'EJOURNAL_POST_VOID', 0, 0, 'AQ==', '_secPrivilege_EJOURNAL_POST_VOID', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'EJOURNAL_REBATE_RECEIPT', 0, 0, 'AQ==', '_secPrivilege_EJOURNAL_REBATE_RECEIPT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'EJOURNAL_REPRINT_RECEIPT', 0, 0, 'AQ==', '_secPrivilege_EJOURNAL_REPRINT_RECEIPT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'END_COUNT_OTHER_TILL', 0, 0, 'EA==', '_secPrivilege_END_COUNT_OTHER_TILL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OVERRIDE_FOREIGN_CHANGE_EXCEEDS_FUNDS', 1, 1, 'EA==', '_secPrivilege_OVERRIDE_FOREIGN_CHANGE_EXCEEDS_FUNDS', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'FISCAL_PRINTER_OVERRIDE', 1, 1, 'AQ==', '_secPrivilege_FISCAL_PRINTER_OVERRIDE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'FOREIGN_CURRENCY_MAINT', 0, 1, 'AQ==', '_secPrivilege_FOREIGN_CURRENCY_MAINT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'INITIATE_INVENTORY_COUNT', 0, 1, 'EA==', '_secPrivilege_INITIATE_INVENTORY_COUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'INVALID_AR_MANUAL_AUTH_CODE', 0, 1, 'EA==', '_secPrivilege_INVALID_AR_MANUAL_AUTH_CODE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'INV_DOC_EDIT_CLOSED_DATA', 1, 1, 'AQ==', '_secPrivilege_INV_DOC_EDIT_CLOSED_DATA', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'ISSUE_TILL', 0, 1, 'AQ==', '_secPrivilege_ISSUE_TILL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'JMX_ACCESS', 0, 0, 'AQ==', '_secPrivilege_JMX_ACCESS', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'KEEP_CASH_DRAWER_OPEN', 0, 1, 'AQ==', '_secPrivilege_KEEP_CASH_DRAWER_OPEN', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'LAYAWAY_CANCEL', 0, 1, 'AQ==', '_secPrivilege_LAYAWAY_CANCEL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'LOG_IN', 0, 0, 'AQ==', '_secPrivilege_LOG_IN', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'LOG_IN_TO_SYSTEM', 0, 0, 'AQ==', '_secPrivilege_LOG_IN_TO_SYSTEM', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'MAINTAIN_EMPLOYEE_MESSAGES', 0, 0, 'AQ==', '_secPrivilege_MAINTAIN_EMPLOYEE_MESSAGES', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CHEETAH_CLIENT_DEVICE_ACCESS', 0, 1, 'EA==', '_secPrivilege_CHEETAH_CLIENT_DEVICE_ACCESS', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'MODIFY_DISCOUNT', 0, 1, 'AQ==', '_secPrivilege_MODIFY_DISCOUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'NO_SALE', 0, 0, 'AQ==', '_secPrivilege_NO_SALE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'NOT_FOUND_VOUCHER', 0, 1, 'EA==', '_secPrivilege_NOT_FOUND_VOUCHER', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OFFLINE_TRANS_REVIEW', 0, 1, 'EA==', '_secPrivilege_OFFLINE_TRANS_REVIEW', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OPEN_STORE_BANK', 0, 0, 'EA==', '_secPrivilege_OPEN_STORE_BANK', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'ORDER_REJECT', 0, 1, 'AQ==', '_secPrivilege_ORDER_REJECT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OVER_TENDER_ABOVE_CONFIGURED_AMOUNT', 0, 1, 'AQ==', '_secPrivilege_OVER_TENDER_ABOVE_CONFIGURED_AMOUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OVERRIDE_COUPON_EXPIRED', 1, 1, 'AQ==', '_secPrivilege_OVERRIDE_COUPON_EXPIRED', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OVERRIDE_COUPON_NOT_EFFECTIVE', 1, 1, 'AQ==', '_secPrivilege_OVERRIDE_COUPON_NOT_EFFECTIVE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OVERRIDE_LAYAWAY_CANCEL_TO_ESCROW', 0, 0, 'AQ==', '_secPrivilege_OVERRIDE_LAYAWAY_CANCEL_TO_ESCROW', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OVERRIDE_LAYAWAY_DEPOSIT_AMOUNT', 0, 1, 'AQ==', '_secPrivilege_OVERRIDE_LAYAWAY_DEPOSIT_AMOUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OVERRIDE_SPEC_ORDER_CANCEL_TO_ESCROW', 0, 0, 'AQ==', '_secPrivilege_OVERRIDE_SPEC_ORDER_CANCEL_TO_ESCROW', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OVERRIDE_SPECIAL_ORDER_DEPOSIT_AMOUNT', 0, 1, 'AQ==', '_secPrivilege_OVERRIDE_SPECIAL_ORDER_DEPOSIT_AMOUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OVERRIDE_VOUCHER_EXPIRED', 1, 1, 'AQ==', '_secPrivilege_OVERRIDE_VOUCHER_EXPIRED', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OVERRIDE_VOUCHER_NOT_EFFECTIVE', 1, 1, 'AQ==', '_secPrivilege_OVERRIDE_VOUCHER_NOT_EFFECTIVE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OVERRIDE_WORK_ORDER_DEPOSIT_AMOUNT', 0, 1, 'AQ==', '_secPrivilege_OVERRIDE_WORK_ORDER_DEPOSIT_AMOUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'PAYROLL_EDIT_AFTER_POST', 0, 0, 'AQ==', '_secPrivilege_PAYROLL_EDIT_AFTER_POST', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'PAYROLL_MAINTENANCE', 0, 1, 'AQ==', '_secPrivilege_PAYROLL_MAINTENANCE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'PAYROLL_REPOST', 0, 0, 'AQ==', '_secPrivilege_PAYROLL_REPOST', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'PRINT_CUSTOMER', 0, 0, 'AQ==', '_secPrivilege_PRINT_CUSTOMER', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'PRINT_GIFT_RCPTS_BEYOND_LIMIT', 0, 1, 'AQ==', '_secPrivilege_PRINT_GIFT_RCPTS_BEYOND_LIMIT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RECEIVE_ENTIRE_ASN', 0, 0, 'AQ==', '_secPrivilege_RECEIVE_ENTIRE_ASN', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RECEIVING', 0, 0, 'AQ==', '_secPrivilege_RECEIVING', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RECEIVING_EDIT_CLOSED_DATA', 0, 1, 'AQ==', '_secPrivilege_RECEIVING_EDIT_CLOSED_DATA', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RECEIVING_MAX_QUANTITY_THRESHOLD', 1, 1, 'AQ==', '_secPrivilege_RECEIVING_MAX_QUANTITY_THRESHOLD', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RECONCILE_TILL', 0, 0, 'EA==', '_secPrivilege_RECONCILE_TILL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RECONCILE_STORE_BANK', 0, 0, 'EA==', '_secPrivilege_RECONCILE_STORE_BANK', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'REFUND_TENDER_ABOVE_CONFIGURED_AMOUNT', 0, 1, 'AQ==', '_secPrivilege_REFUND_TENDER_ABOVE_CONFIGURED_AMOUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'REFUND_TENDER_BALANCE', 0, 1, 'AQ==', '_secPrivilege_REFUND_TENDER_BALANCE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'REGENERATE_PAYROLL_FILE', 1, 0, 'AQ==', '_secPrivilege_REGENERATE_PAYROLL_FILE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RELOAD_GIFT_CARD', 0, 0, 'AQ==', '_secPrivilege_RELOAD_GIFT_CARD', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'REMOVE_OTHER_TILL', 0, 0, 'EA==', '_secPrivilege_REMOVE_OTHER_TILL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'REMOVE_TILL', 0, 0, 'AQ==', '_secPrivilege_REMOVE_TILL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'REPAIR_INVOICING', 0, 0, 'AQ==', '_secPrivilege_REPAIR_INVOICING', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'REPORT_DELETE_CORPORATE', 0, 1, 'AQ==', '_secPrivilege_REPORT_DELETE_CORPORATE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'REPORT_DELETE_PERSONAL', 0, 1, 'AQ==', '_secPrivilege_REPORT_DELETE_PERSONAL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'REPORT_DELETE_STORE', 0, 1, 'AQ==', '_secPrivilege_REPORT_DELETE_STORE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'REPRINT_PREVIOUS_DAY', 0, 1, 'AQ==', '_secPrivilege_REPRINT_PREVIOUS_DAY', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RETURN_EXCEED_MAX_THRESHOLD', 0, 1, 'AQ==', '_secPrivilege_RETURN_EXCEED_MAX_THRESHOLD', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RETURN_GIFT_CARD', 1, 1, 'AQ==', '_secPrivilege_RETURN_GIFT_CARD', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RETURN_GIFT_CERTIFICATE', 1, 1, 'AQ==', '_secPrivilege_RETURN_GIFT_CERTIFICATE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RETURN_STORE_CREDIT', 1, 1, 'AQ==', '_secPrivilege_RETURN_STORE_CREDIT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RETURN_CROSS_BORDER', 0, 1, 'EA==', '_secPrivilege_RETURN_CROSS_BORDER', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RETURN_ITEM', 0, 0, 'AQ==', '_secPrivilege_RETURN_ITEM', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RETURN_ITEM_NOT_IN_ORIG_TRANS', 0, 1, 'AQ==', '_secPrivilege_RETURN_ITEM_NOT_IN_ORIG_TRANS', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RETURN_MAX_ITEM_PRICE_VALIDATION', 0, 1, 'AQ==', '_secPrivilege_RETURN_MAX_ITEM_PRICE_VALIDATION', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RETURN_MIN_ITEM_PRICE_VALIDATION', 0, 1, 'AQ==', '_secPrivilege_RETURN_MIN_ITEM_PRICE_VALIDATION', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RETURN_NOT_RETURNABLE_ITEM', 0, 1, 'EA==', '_secPrivilege_RETURN_NOT_RETURNABLE_ITEM', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RETURN_NOT_RETURNABLE_ITEM_OVER_MAXDAYS', 0, 1, 'AQ==', '_secPrivilege_RETURN_NOT_RETURNABLE_ITEM_OVER_MAXDAYS', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RETURN_QUANTITY_EXCEED_ORIG_QUANTITY', 0, 0, 'EA==', '_secPrivilege_RETURN_QUANTITY_EXCEED_ORIG_QUANTITY', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RETURN_TILL', 0, 1, 'AQ==', '_secPrivilege_RETURN_TILL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RETURN_WITH_NON_RETURN_ITEM', 0, 1, 'AQ==', '_secPrivilege_RETURN_WITH_NON_RETURN_ITEM', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RETURN_KIT', 0, 1, 'AQ==', '_secPrivilege_RETURN_KIT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'SEARCH_INVENTORY_COUNT', 0, 1, 'EA==', '_secPrivilege_SEARCH_INVENTORY_COUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'SELL_GIFT_CARD', 0, 0, 'AQ==', '_secPrivilege_SELL_GIFT_CARD', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'SELL_GIFT_CERTIFICATE', 0, 0, 'AQ==', '_secPrivilege_SELL_GIFT_CERTIFICATE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'SELL_ITEM', 0, 0, 'AQ==', '_secPrivilege_SELL_ITEM', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'SELL_ITEM_NOT_ON_FILE', 0, 1, 'AQ==', '_secPrivilege_SELL_ITEM_NOT_ON_FILE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'SELL_NON_PHYSICAL', 0, 0, 'AQ==', '_secPrivilege_SELL_NON_PHYSICAL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'SHIPPER_METHOD_OVERRIDE', 0, 1, 'EA==', '_secPrivilege_SHIPPER_METHOD_OVERRIDE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'SHIPPING_EDIT_CLOSED_DATA', 1, 1, 'AQ==', '_secPrivilege_SHIPPING_EDIT_CLOSED_DATA', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'SPECIAL_ORDER_CANCEL', 0, 1, 'AQ==', '_secPrivilege_SPECIAL_ORDER_CANCEL', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'STORE_BANK_CASH_DEPOSIT', 0, 1, 'AQ==', '_secPrivilege_STORE_BANK_CASH_DEPOSIT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'TENDER_ABOVE_CONFIGURED_AMOUNT', 0, 1, 'AQ==', '_secPrivilege_TENDER_ABOVE_CONFIGURED_AMOUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'TENDER_BELOW_CONFIGURED_AMOUNT', 0, 1, 'AQ==', '_secPrivilege_TENDER_BELOW_CONFIGURED_AMOUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'TENDER_EXCHANGE', 0, 0, 'AQ==', '_secPrivilege_TENDER_EXCHANGE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'TILL_MANAGEMENT', 0, 1, 'AQ==', '_secPrivilege_TILL_MANAGEMENT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'TILL_COUNT_OVER_THRESHOLD_OVERRIDE', 0, 1, 'EA==', '_secPrivilege_TILL_COUNT_OVER_THRESHOLD_OVERRIDE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'TIME_CLOCK', 0, 0, 'AQ==', '_secPrivilege_TIME_CLOCK', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'TIME_CLOCK_DURATION', 0, 1, 'EA==', '_secPrivilege_TIME_CLOCK_DURATION', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'TIMECARD_MAINTENANCE', 0, 0, 'AQ==', '_secPrivilege_TIMECARD_MAINTENANCE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'TOTAL_LAYAWAY_ITEM_PRICE_BELOW_MIN', 0, 1, 'AQ==', '_secPrivilege_TOTAL_LAYAWAY_ITEM_PRICE_BELOW_MIN', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'TOTAL_SP_ORDER_ITEM_PRICE_BELOW_MIN', 0, 0, 'AQ==', '_secPrivilege_TOTAL_SP_ORDER_ITEM_PRICE_BELOW_MIN', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'TSE_MANAGER', 1, 1, 'AQ==', '_secPrivilege_TSE_MANAGER', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'TSE_ERROR_MANAGER', 1, 1, 'AQ==', '_secPrivilege_TSE_ERROR_MANAGER', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'UNLOCK_OTHERS_REGISTER', 1, 0, 'AQ==', '_secPrivilege_UNLOCK_OTHERS_REGISTER', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'UNLOCKABLE', 0, 0, 'EA==', '_secPrivilege_UNLOCKABLE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'UNPAUSE_SELF_CHECKOUT', 1, 1, 'EA==', '_secPrivilege_UNPAUSE_SELF_CHECKOUT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'VIEW_ALL_TASKS', 0, 0, 'EA==', '_secPrivilege_VIEW_ALL_TASKS', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'VIEW_ALL_BLACKBOOK_CUSTOMERS', 0, 0, 'EA==', '_secPrivilege_VIEW_ALL_BLACKBOOK_CUSTOMERS', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'VIEW_CUSTOMER', 0, 0, 'AQ==', '_secPrivilege_VIEW_CUSTOMER', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'VIEW_TIMECARD', 0, 0, 'AQ==', '_secPrivilege_VIEW_TIMECARD', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'VOID_DISCOUNT', 0, 1, 'AQ==', '_secPrivilege_VOID_DISCOUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'VOID_LINE', 0, 1, 'AQ==', '_secPrivilege_VOID_LINE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'VOID_TENDER', 0, 1, 'AQ==', '_secPrivilege_VOID_TENDER', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'RETURN_ITEM_NOT_IN_HISTORY', 0, 1, 'EA==', '_secPrivilege_RETURN_ITEM_NOT_IN_HISTORY', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'HOUSE_ACCNT_MANAGER_OVERRIDE', 0, 1, 'EA==', '_secPrivilege_HOUSE_ACCNT_MANAGER_OVERRIDE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'MANUAL_CUSTOMER_BIRTH_DATE_ENTRY', 0, 1, 'EA==', '_secPrivilege_MANUAL_CUSTOMER_BIRTH_DATE_ENTRY', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'SUPERVISOR_LOGIN', 0, 1, 'EA==', '_secPrivilege_SUPERVISOR_LOGIN', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'REPLENISHMENT_ORDER_FORCE_CLOSE', 1, 1, 'EA==', '_secPrivilege_REPLENISHMENT_ORDER_FORCE_CLOSE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CHECK_FOR_UPDATES', 0, 1, 'EA==', '_secPrivilege_CHECK_FOR_UPDATES', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OVERRIDE_PRESALE_DEPOSIT_AMOUNT', 0, 1, 'AQ==', '_secPrivilege_OVERRIDE_PRESALE_DEPOSIT_AMOUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'PRINT_RAIN_CHECKS', 0, 1, 'AQ==', '_secPrivilege_PRINT_RAIN_CHECKS', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'BLIND_RETURNS_AMOUNT_THRESHOLD', 0, 1, 'EA==', '_secPrivilege_BLIND_RETURNS_AMOUNT_THRESHOLD', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OVERRIDE_LOWEST_RETURN_PRICE', 0, 1, 'EA==', '_secPrivilege_OVERRIDE_LOWEST_RETURN_PRICE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'FLIGHT_INFO_ENTRY_MANAGER_OVERRIDE', 0, 1, 'EA==', '_secPrivilege_FLIGHT_INFO_ENTRY_MANAGER_OVERRIDE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'QUANTITY_UNAVAILABLE', 0, 1, 'EA==', '_secPrivilege_QUANTITY_UNAVAILABLE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OVERRIDE_ONHOLD_DEPOSIT_AMOUNT', 0, 1, 'AQ==', '_secPrivilege_OVERRIDE_ONHOLD_DEPOSIT_AMOUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OVERRIDE_LOCALORDER_DEPOSIT_AMOUNT', 0, 0, 'AAA=', '_secPrivilege_OVERRIDE_LOCALORDER_DEPOSIT_AMOUNT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'MANAGE_IP_CASH_DRAWER', 0, 1, 'EA==', '_secPrivilege_MANAGE_IP_CASH_DRAWER', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'VIEW_LAST_LOGGED_IN_USERS', 0, 1, 'EA==', '_secPrivilege_VIEW_LAST_LOGGED_IN_USERS', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'ISSUE_INVOICE_FROM_EJ', 0, 0, 'AQ==', '_secPrivilege_ISSUE_INVOICE_FROM_EJ', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'REPRINT_INVOICE_FROM_EJ', 0, 0, 'AQ==', '_secPrivilege_REPRINT_INVOICE_FROM_EJ', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'REPRINT_LAST_INVOICE', 0, 0, 'AQ==', '_secPrivilege_REPRINT_LAST_INVOICE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'POST_VOID_INVOICE_FROM_EJ', 0, 0, 'AQ==', '_secPrivilege_POST_VOID_INVOICE_FROM_EJ', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'SAFT_FILE_GENERATE', 0, 0, 'AQ==', '_secPrivilege_SAFT_FILE_GENERATE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'STOCK_FILE_GENERATE', 0, 0, 'AQ==', '_secPrivilege_STOCK_FILE_GENERATE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'PT_RESET_SEQUENCES', 0, 0, 'AQ==', '_secPrivilege_PT_RESET_SEQUENCES', GETUTCDATE(), 'ASQBDATA',GETUTCDATE(), 'ASQBDATA');

INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'DE_GENERATE_GOBD', 0, 1, 'EA==', '_secPrivilege_DE_GENERATE_GOBD', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'DE_EXPORT_DSFINVK', 0, 1, 'EA==', '_secPrivilege_DE_EXPORT_DSFINVK', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

--CNP tender privilege
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'CUSTOMER_NOT_PRESENT_TENDER_MANAGER_OVERRIDE', 0, 1, 'EA==', '_secPrivilege_CUSTOMER_NOT_PRESENT_TENDER_MANAGER_OVERRIDE', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

--24x7 Privileges
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'END_OF_DAY_PROCESS', 0, 0, 'EA==', '_secPrivilege_END_OF_DAY_PROCESS', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

--Xenvironment privileges
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'LOGIN_TO_XENVIRONMENT', 1, 1, 'AQ==', '_secPrivilege_LOGIN_TO_XENVIRONMENT', getDate(), 'ASQBDATA', getDate(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'SYSTEM_ADMIN', 1, 1, 'EA==', '_secPrivilege_SYSTEM_ADMIN', getDate(), 'ASQBDATA', getDate(), 'ASQBDATA');

--Countrypack: France Privileges
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'FR_DATABASE_TAMPERING_CHECK_ERROR', 0, 1, 'EA==', '_secPrivilege_FR_DATABASE_TAMPERING_CHECK_ERROR', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'FR_INSERT_JET_COMMENT', 0, 1, 'EA==', '_secPrivilege_FR_INSERT_JET_COMMENT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'FR_JET_REPORT', 0, 1, 'EA==', '_secPrivilege_FR_JET_REPORT', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'FR_ARCHIVE_STORE', 0, 1, 'EA==', 'Archive full store', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

--Airside: return validation override privileges
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'OVERRIDE_FLIGHT_RETURN_VALIDATION', 1, 1, 'EA==', '_secPrivilege_OVERRIDE_FLIGHT_RETURN_VALIDATION', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

--Self Checkout Management Console Administrator
INSERT INTO sec_privilege (organization_id, privilege_type, authentication_req, overridable_flag, group_membership, description, create_date, create_user_id, update_date, update_user_id) VALUES ($(OrgID) , 'SCO_MGMT_CONSOLE_ADMIN', 0, 1, 'EA==', '_secPrivilege_SCO_MGMT_CONSOLE_ADMIN', GETUTCDATE(), 'ASQBDATA', GETUTCDATE(), 'ASQBDATA');

